# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20170927_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
